import assert from 'node:assert/strict'
import test from 'node:test'
import { parseStructuredQueryArgv } from '../src/google/cliStructuredQuery.ts'
import { buildGoogleQuery } from '../src/google/queryBuilder.ts'

test('builds the consulting-report PDF query from structured CLI flags', () => {
  const argv = [
    '--group-start',
    '--site',
    'bain.com',
    '--or-op',
    '--site',
    'bainandcompany.com',
    '--or-op',
    '--site',
    'bcg.com',
    '--or-op',
    '--site',
    'bcg-group.com',
    '--or-op',
    '--site',
    'analysisgroup.com',
    '--group-end',
    '--filetype',
    'pdf',
    '--not',
    'tax',
    '--not',
    'notice',
    '--not',
    'audit',
    '--not',
    'privacy',
    '--not',
    'careers',
    '--group-start',
    'report',
    '--or-op',
    'outlook',
    '--or-op',
    'trends',
    '--or-op',
    'survey',
    '--or-op',
    'insights',
    '--or-op',
    'infographic',
    '--or-op',
    '--exact',
    'fact sheet',
    '--or-op',
    '--exact',
    'one-pager',
    '--or-op',
    'placemat',
    '--or-op',
    '--exact',
    'at a glance',
    '--group-end',
    '--group-start',
    'chart',
    '--or-op',
    'graph',
    '--or-op',
    'figure',
    '--or-op',
    'exhibit',
    '--group-end',
  ]

  const plan = buildGoogleQuery({
    terms: [],
    exact: [],
    anyOf: [],
    exclude: [],
    site: [],
    excludeSite: [],
    filetype: [],
    excludeFiletype: [],
    intitle: [],
    allintitle: [],
    inurl: [],
    allinurl: [],
    intext: [],
    allintext: [],
    src: [],
    imagesize: [],
    after: undefined,
    before: undefined,
    logic: [],
    structuredTokens: parseStructuredQueryArgv(argv),
    raw: [],
  })

  assert.equal(
    plan.query,
    '(site:bain.com OR site:bainandcompany.com OR site:bcg.com OR site:bcg-group.com OR site:analysisgroup.com) filetype:pdf -tax -notice -audit -privacy -careers (report OR outlook OR trends OR survey OR insights OR infographic OR "fact sheet" OR "one-pager" OR placemat OR "at a glance") (chart OR graph OR figure OR exhibit)',
  )

  assert.deepEqual(plan.notes, [
    '`--group-start` / `--group-end` add grouped query clauses. Google commonly accepts parentheses, but grouping is outside this repo\'s stable-official operator subset.',
    '`OR` is taken from Google developer documentation, but it is not in the current core Help/Search Central operator shortlist.',
  ])
})
